### ISSUE TITLE
Doesn't actually display any chat messages.

### ISSUE THREAD

**Issue by Fullmight** [Hotrian/HeadlessOverlayToolkit#1]
Pretty simple issue. Followed instructions as on download page. No issues except that after successfully connecting to twitch chat, no messages are ever displayed.

**Comment by Hotrian** [comment]
What channel are you trying to connect to?

Edit: Can you try connecting to a different channel and see if it works there? You shouldn't include the # in the channel box, just the name of the twitch streamer. Also please try entering the channel name in all lowercase if you aren't already. Though [this shouldn't matter](https://github.com/Hotrian/HeadlessOverlayToolkit/blob/twitchtest/Assets/HOTK/Twitch/TwitchChatTester.cs#L79).

**Comment by Hotrian** [comment]
Can you try [the latest release](https://github.com/Hotrian/HeadlessOverlayToolkit/releases) and see if you are actually able to join the channel?

**Comment by Fullmight** [comment]
Tried the latest release. I get logged in, connecting to chat, acknowledging client capabilities twice, and that's it nothing more.

Still shows up in game fine but no chat messages are loaded.

**Comment by Fullmight** [comment]
Ahhh derp. Got it working. Thought I had to enter the full channel address not the channel tag.

**Comment by Hotrian** [comment]
Thanks for the feedback! I'll try and add URL detection in the future so it can perhaps extract and use just the channel tag if the full URL is entered, or at least show a warning.
