### ISSUE TITLE
How to build as an Overlay instead of VR application?

### ISSUE THREAD

**Issue by James-Firth** [Hotrian/HeadlessOverlayToolkit#5]
Hi again,

I've built a small application with your awesome toolkit to make some text appear.

However, I'm unable to run my project at the same time as a game. I see you have an example with your overlay working at the same time as Tiltbrush.

How can I get it to run as an overlay? 

This might be something useful to add to `README.md` to help beginners such as myself

**Comment by Hotrian** [comment]
Hey if you check #4 I mentioned this is because of Unity 5.4's Native VR Support. I'm assuming you're still using Unity 5.4? bjennings made some changes to the SteamVR code to make it ignore 5.4's native code; check #4 I gave a link (I'm mobile right now). 

This repo is only for Unity 5.3.5f1 right now, but I believe bjennings' changes will allow this to run on 5.4 as well if you don't have native VR support enabled.

**Comment by James-Firth** [comment]
I'm actually running 5.3.5 on this other machine at the moment (sorry should have mentioned that). But good to know for my machine with 5.4.

**Comment by Hotrian** [comment]
To be clear though, bjennings' changes don't actually disable the Native VR Support. If you've enabled it, you'll have to disable it again for his/her workaround to work. I believe you can do this under Player Settings > VR Support but that might not be the exact location :).

**Comment by Hotrian** [comment]
Oh on 5.3.5f1 it's still forcing other applications to close? I'll have to look into that :o.

**Comment by James-Firth** [comment]
Ah that's good to know!

Yeah on 5.3.5f it seems to be forcing other applications to close. It's possible I just missed a build setting or something as I haven't built many Unity apps before.

**Comment by Hotrian** [comment]
Hey, so I just tested this against Unity 5.3.5f1 and Job Simulator and I didn't have any issues. Both were able to open just fine. If you are building off of HOTK can you try cloning it again? If you are trying to import HOTK into your project, can you make sure you are using [this version of SteamVR.cs](https://github.com/Hotrian/HeadlessOverlayToolkit/blob/master/Assets/SteamVR/Scripts/SteamVR.cs)? In specific, [this line](https://github.com/Hotrian/HeadlessOverlayToolkit/blob/master/Assets/SteamVR/Scripts/SteamVR.cs#L78) is what tells OpenVR to Init HOTK as an Overlay application.

**Comment by James-Firth** [comment]
Ah! That was the problem, I had the wrong version of SteamVR.cs!

Thank you very much!
